---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[cobbler::default]
    attributes:
      cobbler:
        dhcp_network:
          network: '10.0.2.0'
          netmask: '255.255.255.0'
          routers: '10.0.2.1'
          name_servers: '10.0.2.1'
          range: '10.0.2.100 10.0.2.200'
